# This is a basic workflow to help you get started with Actions

name: lukaliku

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      - name: Run Android In Docker Image
        run: |
           echo script By NetFlex
           sleep 2
           echo Loading Script
           sleep 3
           docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="$Env:PHONE_AUTH" --name android-container budtmo/docker-android-x86-8.1
           curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
           unzip ngrok.zip
           ./ngrok authtoken $Env:NGROK_AUTH_TOKEN
           ./ngrok http 6080 -region ap
        env: 
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          PHONE_AUTH: ${{ secrets.PHONE_AUTH }}
